homeassistant: !include config/homeassistant.yaml
http: !include config/http.yaml

frontend:
config:
updater:
discovery:
conversation:
map:
sun:
shopping_list:

lovelace:
  mode: yaml

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarm_user
  password: !secret alarm_pass
  code: !secret alarm_code

ring:
  username: !secret ring_user
  password: !secret ring_pass

influxdb:
  host: !secret influx_host
  port: !secret influx_port
  database: !secret influx_db
  default_measurement: state
  include:
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.sabnzbd_left
      - sensor.sabnzbd_queue_count
      - sensor.sabnzbd_speed
      - light.deck_light
      - light.dining_room_light
      - light.gym_light_1
      - light.gym_light_2
      - light.gym_light_3
      - light.lounge_light
      - light.office_light
      - light.sams_light
      - light.workbench_light
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.network_in_eth0
      - sensor.network_out_eth0
      - binary_sensor.back_door
      - binary_sensor.front_door
      - binary_sensor.garage_door
      - sensor.disk_use_percent_config
      - binary_sensor.anet_a8_printing
      - sensor.lounge_humidity
      - sensor.lounge_preassure
      - sensor.lounge_temperature_bmp180
      - sensor.lounge_temperature_dht11
  tags_attributes:
    - friendly_name
    - unit_of_measurement
    - icon
    - supported_features
    - device_class
    - attribution
    - server_country
    - server_id
    - server_name
  # exclude:
  #   entities:
  #     - sensor.sonarr_wanted
  #     - sensor.sonarr_disk_space
  #     - sensor.sonarr_series
  #     - sensor.sonarr_upcoming
  #     - light.bedroom
  #   domains:
  #     - automation
  #     - weblink
  #     - group
  #     - alarm_control_panel
  #     - camera
  tags:
    host: hass
  
group: !include_dir_merge_named config/groups
weblink: !include config/web_links.yaml
recorder: !include config/recorder.yaml
history: !include config/history.yaml
logbook: !include config/logbook.yaml
logger: !include config/logger.yaml
switch: !include_dir_list config/switches
light: !include_dir_list config/lights
input_select: !include config/input_selects.yaml
input_number: !include config/input_numbers.yaml
automation: !include_dir_list config/automations
sensor: !include_dir_list config/sensors
weather: !include config/weather.yaml
device_tracker: !include config/device_tracker.yaml
zone: !include config/zones.yaml
sabnzbd: !include config/sabnzbd.yaml
tts: !include config/tts.yaml
mqtt: !include config/mqtt.yaml
script: !include config/scripts.yaml
octoprint: !include config/octoprint.yaml
camera: !include config/camera.yaml
binary_sensor: !include_dir_list config/binary_sensors