homeassistant:
  name: Home
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 0
  unit_system: metric
  time_zone: Canada/Mountain
  customize: !include customize.yaml

frontend:

recorder:
  db_url: !secret db_mysql

config:

http:
  api_password: !secret http_password

updater:

discovery:

conversation:

history:
  exclude:
    entities:
      - sensor.world_clock_canada
      - sensor.world_clock_south_africa
    domains:
      - group

logbook:

logger:
  default: debug

map:

sun:

sensor:
  - platform: yr
  
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 15
      - 30
      - 45
      
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: load_1m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: processor_use
      - type: last_boot
      
  - platform: worldclock
    time_zone: Canada/Mountain
    name: World Clock Canada
    
  - platform: worldclock
    time_zone: Africa/Johannesburg
    name: World Clock South Africa
      
device_tracker:
  - platform: google_maps
    username: !secret google_user
    password: !secret google_pass
    
zone:
  - name: Gym
    latitude: 53.5301052
    longitude: -113.2932228
    radius: 150
    icon: mdi:dumbbell

tts:
  - platform: google

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass
  

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
