homeassistant:
  name: Home
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 0
  unit_system: metric
  time_zone: Canada/Mountain
  customize: !include customize.yaml

frontend:

weblink:
  entities:
    - name: Lovelace
      url: http://10.0.0.103:8123/lovelace/0
      icon: mdi:cards-heart

recorder:
  db_url: !secret db_mysql

config:

http:
  api_password: !secret http_password
  server_port: 443
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:

discovery:

conversation:

history:
  exclude:
    entities:
      - sensor.world_clock_canada
      - sensor.world_clock_south_africa
      - light.lounge
      - light.workbench
      - light.bedroom
      - light.deck
      - light.dining_room
      - light.office
      - light.sams_room
      - sensor.last_boot
      - sensor.yr_symbol
    domains:
      - group

logbook:
  exclude:
    entities:
      - sensor.world_clock_south_africa
      - sensor.world_clock_canada
      - light.bedroom_light
      - light.bedroom

logger:
  default: debug
  #homeassistant.components.websocket_api: warning

map:

# fan:
#   - platform: mqtt
#     command_topic: "cmnd/sonoff_fan/POWER"
#     state_topic: "cmnd/sonoff_fan/POWER"
#     payload_on: "ON"
#     payload_off: "OFF"
#     name: "Bedroom Fan"

sun:

light:
  - platform: mqtt
    name: "Holiday Lights"
    command_topic: "bruh/mqttstrip/setpower"
    state_topic: "bruh/mqttstrip/setpowerpub"
    rgb_state_topic: "bruh/mqttstrip/setcolorpub"
    rgb_command_topic: "bruh/mqttstrip/setcolor"
    brightness_state_topic: "bruh/mqttstrip/setbrightnesspub"
    brightness_command_topic: "bruh/mqttstrip/setbrightness"
    optimistic: false
    
  - platform: mqtt
    name: "Kitchen Lights"
    command_topic: "bruh/kitchen/setpower"
    state_topic: "bruh/kitchen/setpowerpub"
    rgb_state_topic: "bruh/kitchen/setcolorpub"
    rgb_command_topic: "bruh/kitchen/setcolor"
    brightness_state_topic: "bruh/kitchen/setbrightnesspub"
    brightness_command_topic: "bruh/kitchen/setbrightness"
    optimistic: false
    
input_select:
  holiday_led_effect:
    name: Holiday LED Effect
    options:
      - "Christmas"
      - "Candy Cane"
      - "Holly Jolly"
      - "Valentine"
      - "Lovey Day"
      - "St Patty"
      - "Easter"
      - "USA"
      - "Independence"
      - "Go Blue"
      - "Hail"
      - "Touchdown"
      - "Halloween"
      - "Punkin"
      - "Thanksgiving"
      - "Turkey Day"
      - "BPM"
      - "Confetti"
      - "Cyclon Rainbow"
      - "Dots"
      - "Fire"
      - "Glitter"
      - "Juggle"
      - "Lightning"
      - "Police All"
      - "Police One"
      - "Rainbow"
      - "Rainbow with Glitter"
      - "Ripple"
      - "Sinelon"
      - "Solid"
      - "Twinkle"
    initial: "Solid"
  
  esp8266:
    name: ESP8266
    options:
      - "mqttstrip"
      - "strip2"
      - "kitchen"
    initial: "mqttstrip"
    
input_number:
  animation_speed:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
    
automation: 
  - alias: "Holiday Input Effect"
    initial_state: True
    hide_entity: False
    trigger:
    - platform: state
      entity_id: input_select.holiday_led_effect
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/{{ states('input_select.esp8266') }}/seteffect"
          payload: '{{ trigger.to_state.state | string }}'

  - alias: "Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/{{ states('input_select.esp8266') }}/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'

sensor:
  - platform: yr
  
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 15
      - 30
      - 45
      
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: processor_use
      - type: last_boot
      
  - platform: worldclock
    time_zone: Canada/Mountain
    name: World Clock Canada
    
  - platform: worldclock
    time_zone: Africa/Johannesburg
    name: World Clock South Africa
      
weather:
  - platform: darksky
    api_key: !secret darksky_api
    
device_tracker:
  - platform: google_maps
    username: !secret google_user
    password: !secret google_pass
    
zone:
  - name: Gym
    latitude: 53.5301052
    longitude: -113.2932228
    radius: 150
    icon: mdi:dumbbell

tts:
  - platform: google

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass

group: !include groups.yaml
# automation: !include automations.yaml
script: !include scripts.yaml
