homeassistant:
  name: Home
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 0
  unit_system: metric
  time_zone: Canada/Mountain
  customize: !include customize.yaml

frontend:

weblink:
  entities:
    - name: Lovelace
      url: http://10.0.0.103:8123/lovelace/0
      icon: mdi:cards-heart

recorder:
  db_url: !secret db_mysql

config:

http:
  api_password: !secret http_password

updater:

#binary_sensor:
#  - platform: mqtt
#    state_topic: "tele/RF_Bridge/RESULT"
#    name: 'Garage Motion'
#    value_template: '{{value_json.RfReceived.Data}}'
#    payload_on: '000001'
#    device_class: motion
#    optimistic: false
#    qos: 1
#    retain: false

discovery:

conversation:

history:
  exclude:
    entities:
      - sensor.world_clock_canada
      - sensor.world_clock_south_africa
      - light.lounge
      - light.workbench
      - light.bedroom
      - light.deck
      - light.dining_room
      - light.office
      - light.sams_room
      - sensor.last_boot
      - sensor.yr_symbol
    domains:
      - group

logbook:
  exclude:
    entities:
      - sensor.world_clock_south_africa
      - sensor.world_clock_canada
      - light.bedroom_light
      - light.bedroom

logger:
  default: debug

map:

# fan:
#   - platform: mqtt
#     command_topic: "cmnd/sonoff_fan/POWER"
#     state_topic: "cmnd/sonoff_fan/POWER"
#     payload_on: "ON"
#     payload_off: "OFF"
#     name: "Bedroom Fan"

sun:

# light:
#   - platform: mqtt
#     name: "D1mini ws2812"
#     command_topic: "cmnd/d1test/power"
#     state_topic: "stat/d1test/POWER"
#     rgb_state_topic: "stat/d1test/color"
#     rgb_command_topic: "cmnd/d1test/color"
#     brightness_state_topic: "stat/d1test/dimmer"
#     brightness_command_topic: "cmnd/d1test/dimmer"
#     retain: false

sensor:
  - platform: yr
  
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 15
      - 30
      - 45
      
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: load_1m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: processor_use
      - type: last_boot
      
  - platform: worldclock
    time_zone: Canada/Mountain
    name: World Clock Canada
    
  - platform: worldclock
    time_zone: Africa/Johannesburg
    name: World Clock South Africa
    
  - platform: darksky
    api_key: !secret darksky_api
    name: DarkSky
    monitored_conditions:
      - temperature
      - cloud_cover
      - humidity
      - pressure
      - temperature_high
      - temperature_low
      
  - platform: octoprint
    name: Anet A8
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage
      
weather:
  - platform: darksky
    api_key: !secret darksky_api
    
device_tracker:
  - platform: google_maps
    username: !secret google_user
    password: !secret google_pass
    
zone:
  - name: Gym
    latitude: 53.5301052
    longitude: -113.2932228
    radius: 150
    icon: mdi:dumbbell

tts:
  - platform: google

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass
  
octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1
  

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
