homeassistant: !include config/homeassistant.yaml
http: !include config/http.yaml

frontend:
config:
updater:
discovery:
conversation:
map:
sun:
shopping_list:

lovelace:
  mode: yaml

group: !include_dir_merge_named config/groups
weblink: !include config/web_links.yaml
recorder: !include config/recorder.yaml
history: !include config/history.yaml
logbook: !include config/logbook.yaml
logger: !include config/logger.yaml
switch: !include_dir_list config/switches
light: !include_dir_list config/lights
input_select: !include config/input_selects.yaml
input_number: !include config/input_numbers.yaml
automation: !include_dir_list config/automations
sensor: !include_dir_list config/sensors
weather: !include config/weather.yaml
device_tracker: !include config/device_tracker.yaml
zone: !include config/zones.yaml
sabnzbd: !include config/sabnzbd.yaml
tts: !include config/tts.yaml
mqtt: !include config/mqtt.yaml
script: !include config/scripts.yaml
octoprint: !include config/octoprint.yaml
camera: !include config/camera.yaml
binary_sensor: !include_dir_list config/binary_sensors