homeassistant:
  name: Home
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 0
  unit_system: metric
  time_zone: Canada/Mountain
  customize: !include customize.yaml


frontend:

recorder:
  db_url: !secret db_mysql

config:

http:
  api_password: !secret http_password

updater:

discovery:

conversation:

history:

logbook:

logger:
  default: debug

map:

sun:

sensor:
  - platform: yr
  
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 15
      - 30
      - 45

tts:
  - platform: google

cloud:

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass
  

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
