# https://home-assistant-lovelace-gallery.netlify.com/#
# https://github.com/ciotlosm/custom-lovelace
# https://sharethelove.io/
# https://www.home-assistant.io/lovelace
# https://www.home-assistant.io/lovelace/alarm-panel/
# https://materialdesignicons.com/

title: Home
views:
  - title: Bob
    icon: mdi:home
    cards:
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.deck_light
          - light.gym
          - light.office_light
          - light.workbench_light
          - light.lounge_lamp
          - light.lounge_light
          - light.sams_light
          - light.dining_room_light
      - type: horizontal-stack
        cards:
          - type: gauge
            name: Download Speed
            unit: 'Mbit/s'
            entity: sensor.speedtest_download
          - type: gauge
            name: Upload Speed
            unit: 'Mbit/s'
            entity: sensor.speedtest_upload
            min: 0
            max: 15
      - type: history-graph
        title: 'Net Performance'
        hours_to_show: 6
        refresh_interval: 60
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
      - type: map
        aspect_ratio: 16:9
        default_zoom: 20
        entities:
          - device_tracker.google_maps_111184378817367767624
          - device_tracker.google_maps_117179315722226620815
          - zone.gym
          - zone.home
      - type: media-control
        entity: media_player.gym_speaker
      - type: sensor
        entity: sensor.speedtest_download
        graph: line
        detail: 2
        hours_to_show: 6
      - type: shopping-list
      - type: weather-forecast
        entity: weather.dark_sky

  - title: Lights
    icon: mdi:lightbulb-on-outline
    cards:
      - type: entity-filter
        entities:
          - entity: light.deck_light
            tap_action:
              action: toggle
          - light.gym
          - light.office_light
          - light.workbench_light
          - light.lounge_lamp
          - light.lounge_light
          - light.sams_light
          - light.dining_room_light
        state_filter:
          - "on"
        card:
          type: glance
          title: Running Lights
          show_name: false
          show_state: false
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.deck_light
        - type: light
          entity: light.gym
          name: Gym
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.office_light
        - type: light
          entity: light.workbench_light
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.lounge_lamp
        - type: light
          entity: light.lounge_light
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.sams_light
        - type: light
          entity: light.dining_room_light
          