# https://home-assistant-lovelace-gallery.netlify.com/#
# https://github.com/ciotlosm/custom-lovelace
# https://sharethelove.io/
# https://www.home-assistant.io/lovelace
# https://www.home-assistant.io/lovelace/alarm-panel/
# https://materialdesignicons.com/

title: Home
views:
  - title: Home
    icon: mdi:home
    cards:
      - type: entity-filter
        show_empty: false
        entities:
          - light.deck_light
          - light.gym
          - light.dining_room_light
          - light.hue_white_lamp_1
          - light.lounge_light
          - light.lounge_lamp
          - light.office_light
          - light.sams_light
          - light.workbench_light
          - switch.kitchen_lights
          - switch.test
          - switch.front_lights
        state_filter:
          - "on"
        card: 
          type: glance
          title: Running Lights
          show_state: false
          columns: 4

      - type: entities
        title: Location Tracking
        entities:
          - device_tracker.google_maps_111184378817367767624
          - device_tracker.google_maps_117179315722226620815

      - type: entities
        title: Times
        entities:
          - sensor.world_clock_canada
          - sensor.world_clock_south_africa

      - type: map
        aspect_ratio: 16:9
        default_zoom: 30
        entities:
          - device_tracker.google_maps_111184378817367767624
          - device_tracker.google_maps_117179315722226620815
          - zone.home
          - zone.gym

  - title: Lights
    icon: mdi:lightbulb-on-outline
    cards:
      - type: markdown
        content: >
          ## Core Light Controls

      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.deck_light
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.gym
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.dining_room_light
            tap_action:
              action: toggle

      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.hue_white_lamp_1
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.lounge_light
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.lounge_lamp
            tap_action:
              action: toggle

      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.office_light
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.sams_light
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.workbench_light
            tap_action:
              action: toggle

      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.kitchen_lights
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.test
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.front_lights
            tap_action:
              action: toggle

      - type: markdown
        content: >
          ## Tweak specific lights

      - type: entities
        title: Gym Lights
        entities:
          - light.gym_light_1
          - light.gym_light_2
          - light.gym_light_3

      - type: entities
        title: MQTT Light Controls
        entities:
          - input_number.animation_speed
          - input_select.esp8266
          - input_select.holiday_led_effect

  - title: Security
    icon: mdi:security
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.alarm_com

      - type: entities
        title: Doors
        entities:
          - binary_sensor.back_door
          - binary_sensor.front_door
          - binary_sensor.garage_door

      - type: entities
        title: Ring Doorbell
        entities:
          - binary_sensor.ring_front_door_ding
          - binary_sensor.ring_front_door_motion
          - camera.front_door

  - title: Audio Players
    icon: mdi:volume-high
    cards:
      - type: media-control
        entity: media_player.bedroom_speaker
      
      - type: media-control
        entity: media_player.gym_speaker
      
      - type: media-control
        entity: media_player.lounge_speaker

      - type: media-control
        entity: media_player.sams_room_speaker

  - title: Internet
    icon: mdi:google-chrome
    cards:
      - type: entities
        title: SABNzbd
        entities:
          - sensor.sabnzbd_left
          - sensor.sabnzbd_queue_count
          - sensor.sabnzbd_speed
          - sensor.sabnzbd_status

      - type: entities
        title: Sonarr
        entities:
          - sensor.sonarr_disk_space
          - sensor.sonarr_series
          - sensor.sonarr_upcoming
          - sensor.sonarr_wanted

      - type: entities
        title: Speedtest.net
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload

      - type: history-graph
        title: 'Shaw Performance'
        hours_to_show: 3
        refresh_interval: 30
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload

  - title: 3D Printers
    icon: mdi:printer-3d
    cards:
      - type: entities
        title: Anet A8
        entities:
          - binary_sensor.anet_a8_printing
          - binary_sensor.anet_a8_printing_error
          - camera.anet_a8
          - sensor.anet_a8_actual_tool0_temp
          - sensor.anet_a8_current_state
          - sensor.anet_a8_job_percentage
          - sensor.anet_a8_target_tool0_temp
          - sensor.anet_a8_time_elapsed
          - sensor.anet_a8_time_remaining
          - switch.anet_a8

      - type: entities
        title: Ender 3
        entities:
          - switch.ender_3

      - type: entities
        title: Links
        entities:
          - weblink.anet_a8

  - title: Host System
    icon: mdi:desktop-classic
    cards:
      - type: entities
        title: Host System
        entities:
          - sensor.disk_use_percent_config
          - sensor.last_boot
          - sensor.memory_use_percent
          - sensor.network_in_eth0
          - sensor.network_out_eth0
          - sensor.processor_use

      - type: history-graph
        title: 'Host Mem | CPU'
        hours_to_show: 1
        refresh_interval: 30
        entities:
          - sensor.processor_use
          - sensor.memory_use_percent

  - title: Probes
    icon: mdi:thermometer
    cards:
      - type: weather-forecast
        entity: weather.dark_sky

      - type: entities
        title: Weather
        entities:
          - sensor.yr_symbol
          - sun.sun

      - type: entities
        title: Lounge Node
        entities:
          - binary_sensor.lounge_esp_light_state
          - light.lounge_esp_light
          - sensor.lounge_humidity
          - sensor.lounge_preassure
          - sensor.lounge_temperature_bmp180
          - sensor.lounge_temperature_dht11

  - title: Automation
    icon: mdi:home-automation
    cards:
      - type: entities
        title: Automations
        entities:
          - automation.alarm_sam_weekday
          - automation.back_door_opened
          - automation.front_door_opened
          - automation.garage_door_opened
          - automation.leds_set_animation_speed
          - automation.leds_set_effect
          - automation.lights_bedroom_off
          - automation.tts_clear_cache