title: Home
views:
  - title: Home
    cards:
      - type: entity-filter
        entities:
          - entity: light.lounge_light
            name: Lounge
            tap_action: toggle
          - entity: light.lounge_lamp
            name: Lounge
            tap_action: toggle
          - entity: light.bedroom_light
            name: Bedroom
            tap_action: toggle
          - entity: light.workbench_light
            name: Workbench
            tap_action: toggle
          - entity: light.deck_light
            name: Deck
            tap_action: toggle
          - entity: light.dining_room_light
            name: Dining
            tap_action: toggle
          - entity: light.office_light
            name: Office
            tap_action: toggle
          - entity: light.sams_light
            name: Sam
            tap_action: toggle
          - entity: light.passage_light_a
            name: Passage
            tap_action: toggle
        state_filter:
          - "on"
        show_empty: false
        card:
          type: glance
          title: Active Lights
          show_state: false
          show_name: true
          
      - type: entities
        title: Hue Lights
        show_header_toggle: true
        entities:
          - light.bedroom_light
          - light.lounge_light
          - light.lounge_lamp
          - light.workbench_light
          - light.deck_light
          - light.dining_room_light
          - light.office_light
          - light.sams_light
          - light.passage_light_a
      - type: entities
        title: Internet Speed
        show_header_toggle: true
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
      - type: entities
        title: Host System
        show_header_toggle: true
        entities:
          - sensor.disk_use_percent_config
          - sensor.last_boot
          - sensor.load_1m
          - sensor.memory_use_percent
          - sensor.network_in_eth0
          - sensor.network_out_eth0
          - sensor.processor_use
      - type: entities
        title: Date & Time
        show_header_toggle: true
        entities:
          - sensor.world_clock_canada
          - sensor.world_clock_south_africa
      - type: entities
        title: DarkSky
        show_header_toggle: true
        entities:
          - sensor.darksky_temperature
          - sensor.darksky_humidity
          - sensor.darksky_daytime_high_temperature
          - sensor.darksky_overnight_low_temperature
          - sensor.darksky_pressure
          - sensor.darksky_cloud_coverage
      - type: entities
        title: Anet A8
        show_header_toggle: true
        entities:
          - sensor.anet_a8_current_state
          - sensor.anet_a8_job_percentage
          - sensor.anet_a8_target_bed_temp
          - sensor.anet_a8_actual_bed_temp
          - sensor.anet_a8_actual_tool0_temp
          - sensor.anet_a8_target_tool0_temp
      - type: entities
        title: all lights
        show_header_toggle: true
        entities:
          - light.basement
          - light.bedroom
          - light.bedroom_light
          - light.deck
          - light.deck_light
          - light.dining_room
          - light.dining_room_light
          - light.lounge
          - light.lounge_lamp
          - light.lounge_light
          - light.office
          - light.office_light
          - light.passage
          - light.passage_light_a
          - light.sams_light
          - light.sams_room
          - light.workbench_light
      - type: entities
        title: all devices
        show_header_toggle: true
        entities:
          - device_tracker.google_maps_111184378817367767624
          - device_tracker.google_maps_117179315722226620815
      - type: media-control
        entity: media_player.lounge_speaker
      - type: media-control
        entity: media_player.gym_speaker
      - type: media-control
        entity: media_player.bedroom_speaker
  - title: 3D Printers
    cards:
      - type: entities
        entities:
          - device_tracker.google_maps_111184378817367767624
          - device_tracker.google_maps_117179315722226620815
      - type: entities
        title: Anet A8
        show_header_toggle: true
        entities:
          - sensor.anet_a8_current_state
          - sensor.anet_a8_job_percentage
          - sensor.anet_a8_target_bed_temp
          - sensor.anet_a8_actual_bed_temp
          - sensor.anet_a8_actual_tool0_temp
          - sensor.anet_a8_target_tool0_temp
      
      