alias: "LEDS - Set Animation Speed"
initial_state: True
hide_entity: False

trigger:
  - platform: state
    entity_id: input_number.animation_speed

action:
  - service: mqtt.publish
    data_template:
      topic: "bruh/{{ states('input_select.esp8266') }}/setanimationspeed"
      payload: '{{ trigger.to_state.state | int }}'