alias: "Christmas Lights (Turn Off)"
initial_state: True
hide_entity: False

trigger:
  - platform: sun
    event: sunrise

action:
  - service: tts.google_say
    data:
      entity_id:
        - media_player.lounge_speaker
        - media_player.bedroom_speaker
        - media_player.gym_speaker
      message: Turning off Christmas lights
  
  - service: switch.turn_off
    data:
      entity_id:
        - switch.window_lights
        - switch.xmas_lights
        - switch.sonoff_mini