platform: systemmonitor
resources:
  - type: disk_use_percent
    arg: /config
  - type: memory_use_percent
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: processor_use
  - type: last_boot