# ============================================================================= 
# Lights 
# ============================================================================= 
light.gym:
  friendly_name: Gym Lights
  icon: mdi:dumbbell

light.deck_light:
  friendly_name: Deck
  icon: mdi:floor-plan

light.workbench_light:
  friendly_name: Workbench Light
  icon: mdi:settings

light.office_light:
  friendly_name: Office Light
  icon: mdi:remote-desktop

light.lounge_lamp:
  friendly_name: Lounge Lamp
  icon: mdi:floor-lamp

light.lounge_light:
  friendly_name: Lounge Overhead
  icon: mdi:television-classic

light.sams_light:
  friendly_name: Sams Light
  icon: mdi:baby-buggy
  
light.gym_light_1:
  friendly_name: Gym Light 1
  icon: mdi:dumbbell

light.gym_light_2:
  friendly_name: Gym Light 2
  icon: mdi:dumbbell

light.gym_light_3:
  friendly_name: Gym Light 3
  icon: mdi:dumbbell

# Hiding
light.lounge:
  hidden: true

light.office:
  hidden: true

light.sams_room:
  hidden: true

light.deck:
  hidden: true

# ============================================================================= 
# Media Players 
# =============================================================================
media_player.chrome_2:
  hidden: true

media_player.pixel_2_xl:
  hidden: true

# ============================================================================= 
# Internet 
# =============================================================================
sensor.speedtest_download:
  friendly_name: Download Speed
  icon: mdi:cloud-download

sensor.speedtest_upload:
  friendly_name: Upload Speed
  icon: mdi:cloud-upload
  
sensor.speedtest_ping:
  friendly_name: Ping
  icon: mdi:mixcloud

  
# ============================================================================= 
# Maps and Tracking
# =============================================================================

device_tracker.google_maps_111184378817367767624:
  friendly_name: Richard

device_tracker.google_maps_117179315722226620815:
  friendly_name: Rachel

  
# ============================================================================= 
# Dates and Times
# =============================================================================
sensor.world_clock_canada:
  friendly_name: Canada
  
sensor.world_clock_south_africa:
  friendly_name: South Africa
  
# ============================================================================= 
# Weather
# =============================================================================
sensor.darksky_cloud_coverage:
  friendly_name: "Cloud Coverage"
  
sensor.darksky_daytime_high_temperature:
  friendly_name: "Day High"
  
sensor.darksky_humidity:
  friendly_name: "Humidity"
  
sensor.darksky_overnight_low_temperature:
  friendly_name: "Day Low"
  
sensor.darksky_pressure:
  friendly_name: "Pressure"
  
sensor.darksky_temperature:
  friendly_name: "Temperature"
  
# ============================================================================= 
# 3D Printers
# =============================================================================
sensor.anet_a8_current_state:
  friendly_name: Status
  icon: mdi:printer-3d
  
sensor.anet_a8_job_percentage:
  friendly_name: "Job %"
  icon: mdi:percent
  
sensor.anet_a8_target_bed_temp:
  friendly_name: "Bed Temp (target)"
  icon: mdi:vector-square
  
sensor.anet_a8_actual_bed_temp:
  friendly_name: "Bed Temp (actual)"
  icon: mdi:vector-square
  
sensor.anet_a8_actual_tool0_temp:
  friendly_name: "Tool Temp (actual)"
  icon: mdi:temperature-celsius
  
sensor.anet_a8_target_tool0_temp:
  friendly_name: "Tool Temp (target)"
  icon: mdi:temperature-celsius
  
# ============================================================================= 
# Internet
# =============================================================================
sensor.sonarr_wanted:
  friendly_name: "Wanted"
  icon: mdi:call-missed

sensor.sonarr_upcoming:
  friendly_name: "Upcomming"
  icon: mdi:calendar-range
  

# ============================================================================= 
# Switches
# =============================================================================

switch.xmas_lights:
  friendly_name: "XMas Lights"
  icon: mdi:pine-tree

switch.window_lights:
  friendly_name: "Bedroom Lights"
  icon: mdi:window-closed

switch.sonoff_mini:
  friendly_name: "Stair Lights"
  icon: mdi:stairs