anet_a8_temps_group:
  name: "A8 Temps"
  entities:
    - sensor.anet_a8_current_state
    - binary_sensor.anet_a8_printing_error
    - sensor.anet_a8_actual_tool0_temp
    - sensor.anet_a8_target_tool0_temp

anet_a8_job_group:
  name: "A8 Current Job"
  entities:
    - binary_sensor.anet_a8_printing
    - sensor.anet_a8_time_elapsed
    - sensor.anet_a8_time_remaining
    - sensor.anet_a8_job_percentage

printer_switches_group:
  name: "Printer Switches"
  entities:
    - switch.anet_a8
    - switch.ender_3