host_system_group:
  name: Host System
  entities:
    - sensor.processor_use
    - sensor.memory_use_percent
    - sensor.disk_use_percent_config
    - sensor.network_in_eth0
    - sensor.network_out_eth0
    - sensor.last_boot