all_lights_view:
  name: All Lights
  view: yes
  icon: mdi:lightbulb-on-outline
  entities:
    - group.esp8266_lights_group
    - light.holiday_lights
    - light.kitchen_lights
    - group.hue_lights_group
    - group.sonoff_group

internet_view:
  name: Internet
  icon: mdi:google-chrome
  view: yes
  entities:
    - group.internet_speed_group
    - group.sonarr_group
    - group.sab_group

speakers_view:
  name: Speakers
  icon: mdi:speaker
  view: yes
  entities:
    - media_player.bedroom_speaker
    - media_player.gym_speaker
    - media_player.lounge_speaker
    - media_player.sams_room_speaker

printers_view:
  name: "3D Printers"
  icon: mdi:printer-3d
  view: yes
  entities:
    - group.anet_a8_temps_group
    - group.anet_a8_job_group
    - camera.anet_a8
    - group.printer_switches_group
    - weblink.anet_a8